version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: expense_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: expense_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
